### ISSUE TITLE
Kicad 7.x support

### ISSUE THREAD

**Issue by Pablo2048** [ubicomplab/ar-debug-workbench#3]
Hi,
thanks for this great tool. Unfortunately I'm not able to make it work under Kicad 7.0.1 (ardw-plugin). I did exported schematic svg into `ardw` folder, but when I click in PCB to plugin action icon nothing happen... Is there any plan to upgrade the plugin code to support new Kicad version?

**Comment by itisishan** [comment]
Thanks Pablo. This system was designed when KiCAD 5.x was current. Unfortunately, we have not been able to provide updates for the new KiCAD versions since then. The code is open source so feel free to fork.  For adjacent projects that are consistently maintained you can check out: https://github.com/openscopeproject/InteractiveHtmlBom <https://github.com/openscopeproject/InteractiveHtmlBom> or https://www.inspectar.com <https://www.inspectar.com/>. Though these tools do not offer exactly the same functionality as ARDW, they can provide some similar features.
